### ISSUE TITLE
Create funder page

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#13]
Fixed page to provide insight into a funder/publisher

**Comment by caprenter** [comment]
I'm not clear how this will work on the architecture we have.

It is possible to search on a publisher which returns:
a list of grants
a faceted list of recipient organisation

I'm not clear if an enhanced publisher page is a refinement of this search page or a separate page all together.

I can see how both of components above would be useful on a publisher page -but I'm maybe not so set on search results being as prominent. However a 'refine' results by what we know from this publisher could be fun (e.g. if they do have categories, dates, values, locations etc it might be useful to explore that data in those faceted contexts)

What can we do about aggregates and graphs? Can we show amount awarded by calendar year as a bar chart for example? (We might want to offer the last five years - but some orgs will potentially go back for many more years)

I would suggest 'total grants given' is problematic as I'm not sure that adding up yearly totals over say 10 years gives you an accurate representation because of inflation etc - although it may be useful when comparing like with like.

Which recipient orgs have had the most awards, and which have had the most money granted (top ten lists?)

**Comment by stevieflow** [comment]
I understood that this page would be more about aggregations rather than search results.  

It may also bring in other assets such as a logo and link to the raw data (via the Salesforce API), but that might be secondary / low importance

However, I can also see the value to further explore / refine the data from a publisher - particularly if they publish extra fields additional to the standard facets, as @caprenter suggests

**Comment by stevieflow** [comment]
It's probably worth clarifying that we currently work with the ``Funding Org`` fields in 360 for this - we have no distinct usage or concept for a "Publisher"...?

**Comment by stevieflow** [comment]
We should also note that on CoVE @ekoner and @kindly  steered us towards some feedback data (number of grants; min size; max size etc) that might be worth considering for this page

**Comment by kindly** [comment]
Done in c218247c
