### ISSUE TITLE
Download these results

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#23]
I would like to know if it is possible to download any set of results as a CSV file - in the 360Giving format

**Comment by kindly** [comment]
This is possible.  However, because each publisher supplies different (and sometimes extra) fields then it will be difficult to make a single CSV that will cover searches across the publishers.  

My main concern is that this should be quick, so also making a multi sheet spreadsheet would be out of the question, if that was needed.

We could limit the CSVs to show some specified fields in the schema (i.e the fields specified on the grants sheet in http://www.threesixtygiving.org/standard/reference/).  But is that good enough?  People downloading may not know there are also extra fields not in this download.

**Comment by robredpath** [comment]
Closing in favour of #127
