### ISSUE TITLE
Selecting multiple facet values

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#27]
I'd like to know how feasible it is to select multiple facet choices at once - eg more than one publisher

**Comment by kindly** [comment]
Many websites do this and they make the user experience confusing. Mainly concerning the counts that appear.  I have used some e-commerce websites that when you click on certain results, that you think should give you certain number of results but do not, and this is normally due to this.

Its hard to explain why this is awkward without seeing it, but I will try:

The counts that appear alongside the facets, display the occurrences of each Funding Org in the current search, including the extra filter if we selected a Recipient Org.  If we allow multiple selection of Funding Orgs and we tick a particular term, what counts should we show against the other Funding Orgs? Currently they would all show a zero count (as no grants have multiple Funding Orgs) and as they have zero they are excluded from the list.  
You could argue that the counts should be the current query, plus facet selection(s) on the Recipient Org, minus any facets on the Funding Org.   This makes those counts look funny as the sum of Recipent Org Facets add up to a different amount then the Funding Org Facets and this is different still to the total result count. Also on selection of multiple facets, sometimes what you have selected now has zero results after selecting something from another facet.

You could also argue its the counts related to just the search term and not including selection of any other facets, but this makes it harder to drill down, as clicking on any other facet will not reduce the list size of the others and potentially have lots of zero counts.

It is also a lot more complicated to write the code for whatever we choose of the above two options.  It also means that we have to do many search queries (one for each facet) which will make the results potentially a lot slower.

It works fine for a set list of facets. i.e if we always showed all the Funding orgs and were happy to show if there was zero results but there are too many Funding orgs for that.

As a side note, in the standard, a single grant is allowed multiple Funding/Recipient Orgs (even though this is not used currently).  In this case you would be able select multiple Funding/Recipient Orgs already, but this is saying that a grant is funded by org x AND org y.  The point of this ticket is asking for org x OR org y, but we would loose the ability to do the AND case if we did this.

**Comment by kindly** [comment]
The first option is done now. I will keep this issue open as I want to judge feedback from doing this.
