### ISSUE TITLE
Sign post GrantNav home page

### ISSUE THREAD

**Issue by morchickit** [OpenDataServices/grantnav#393]
Make sure users understand how to search on the home page. This means : 

- [x] Write how to search on the home page
- [x] remove current search examples from the homepage 
- [ ] Explain that not all publishers are on GrantNav and link to the registry 
- [ ] Explain that GrantNav doesnt have all the answers.

**Comment by robredpath** [comment]
To start on this, it would be useful to understand what users find confusing about the current home page. @morchickit , do we have any testing data or anecdotes of what the things are that people find confusing? Or, are any of the users who've offered to help with testing ones who've raised this as an issue?

**Comment by morchickit** [comment]
The feedback was that it doesn't explain how to search and we see from Piwik that a lot of people ending up just clicking on the example searches (i.e - 'Bristol'). I think we want to delete the example and maybe add a simple text of how to search (as in #37). 

We also need to flag to people what GrantNav can't give them or why they should download the data that they got from their query.

**Comment by robredpath** [comment]
Thanks @morchickit. I wouldn't necessarily take it as a bad thing that people are clicking on the example searches - it may be that they're doing that just as a way to try out the capabilities and interface as part of their own exploration of the interface, learning by doing rather than reading. The original driver behind the examples was that early test users didn't realise the kind of things that they could put into the search box, and so were expecting either very smart Google-style search (eg "youth projects in manchester that received more than £1million between 2013 and 2015" ) or had 'eureka' moments when they discovered from their peers that they could use quotes around phrases. 

I'm putting together some ideas and a mockup for #37 so I'll post there when done. I don't want to overwhelm people with a massive user guide on the front page, but some expanding UI might be the way to go.

**Comment by morchickit** [comment]
Signpost that Search Locations mean Recipient Location only.

**Comment by robredpath** [comment]
So, a lot of this information can already be found in the links in the footer. I think that it's therefore not too much of a leap to assume that people aren't reading the footer links, or taking the time to discover these things. Which is fair enough, it's at least two clicks away, and not brought to the forefront. 

So, how about some key links above the search box? 

![screen shot 2018-03-05 at 16 30 39](https://user-images.githubusercontent.com/641009/36987462-460f166e-2094-11e8-956d-a34a098a9504.png)

Perhaps Getting Started | Advanced Search would be the two useful links here. Getting Started could be a simple page with some screenshots and tips for how to form basic queries, and advanced search could just link to the existing help page, with some edits.

**Comment by morchickit** [comment]
I think this is an excellent idea! I agree that we can assume that people dont look at the footer (not that intuitive), so I think getting this is great.

**Comment by robredpath** [comment]
First two points are done, others are moved to new issues
