### ISSUE TITLE
Two time formats in the GrantNav dump

### ISSUE THREAD

**Issue by morchickit** [OpenDataServices/grantnav#395]
See this screenshot - 
<img width="409" alt="dates grantnav" src="https://user-images.githubusercontent.com/3273659/29679073-abeff248-88f8-11e7-9e63-5d64d7e9de31.PNG">

Why do we get two formats? COVE doesnt need to fix it? What am I missing? 
@stevieflow @robredpath

**Comment by morchickit** [comment]
It is an issue, since I couldn't transform this type: 2016-10-25T00:00:00+00:00 to date format 
--

**Comment by stevieflow** [comment]
This looks to be specifically in terms of the PHF dataset(s):

http://www.phf.org.uk/wp-content/uploads/2017/02/PHF-360Giving-data-UK-grants-to-orgs-under-the-previous-strategy-2006-2015-finalv2.xlsx

http://www.phf.org.uk/wp-content/uploads/2016/09/PHF-360Giving-data-UK-grants-to-orgs-under-the-current-strategy-2015-final-1.xlsx

As you note, these validate through CoVE - with YYYY-MM-DD date format for awardDate.

However, I can also see that PHF have in their xlsx file the column header "Award date" -- rather than "Award Date".  @Bjwebb could that be a reason why this field is converted so?

@morchickit thanks for picking this up via GrantNav.  It might not turn out to be a GN issue - but we can investigate here.

**Comment by morchickit** [comment]
@stevieflow , I also found them on Quixote and EFF, and they have this annoying Z and the end of the date that makes it hard to convert to date.

**Comment by morchickit** [comment]
Currently, this means that it's really hard to convert time through the csv file, and it all has to go through the GrantNav app, I just wonder if it's not effecting the GrantNav filter as well...

**Comment by stevieflow** [comment]
@morchickit the dateTime stamp (with the Z) is allowed by the standard - as this goes back to matters around date formats (not for this thread!)

Thanks for the heads up on those other publishers:

- EFF publish JSON: ``"awardDate" : "2017-02-09T00:00:00.000Z"``
- Quixote: column name "Award Date" - data format: ``19/09/2001``

I would like to establish if the source data does not present awardDate with the correct Title in a spreadsheet, then something happens.  @Bjwebb @robredpath

**Comment by Bjwebb** [comment]
> However, I can also see that PHF have in their xlsx file the column header "Award date" -- rather than "Award Date". @Bjwebb could that be a reason why this field is converted so?
> I would like to establish if the source data does not present awardDate with the correct Title in a spreadsheet, then something happens. @Bjwebb @robredpath

This is nothing to do with titles.

As far as I can see, the output from GrantNav for PHF, Indigo Trust, EFF and Quixote is all as allowed by the standard. The GrantNav output comes from the JSON. EFF publish this directly. Indigo Trust publish a CSV file with strings for dates, so these are used directly. PHF and Quixote publish an Excel file - PHF is formatted correctly and Quixote is not - however, this doesn't matter to our current JSON code, which uses the underlying Excel date information, and applies its own formatting.

This should not be affecting the date filter.

We control the output from GrantNav. Even thought the current output is correct according to the standard, we can reformat it if that makes it more useful for users.

**Comment by morchickit** [comment]
Thanks @Bjwebb !

If we can reformat all of these dates to be dates and not strings, that would be great.
I can reformat them myself on Open Refine, but most of our users dont know how to reformat with it, and Excel cant reformat strings to dates for some reason. 
How much work it will be to reformat this to date? 

@stevieflow , we should discuss dates anyway, but as part of the standard upgrade.

**Comment by Bjwebb** [comment]
> If we can reformat all of these dates to be dates and not strings, that would be great.

In a sense everything in a CSV is strings. My understanding of the problem is that Excel can detect a date formatted like `2017-02-09`, but not one with extra time info `2017-02-09T00:00:00.000Z`.
The fix I'm suggesting is have GrantNav output the former in the CSV (when the time info is all zeroes). This should be fairly straightforward to do.

**Comment by morchickit** [comment]
Closing this and opening a new issue.
